### ISSUE TITLE
GetInfo call returns: "unmarshal v1: cannot parse field name"

### ISSUE THREAD

**Issue by 0xBEEFCAF3** [Kixunil/loptos#9]
Using lnd version: 0.14.2-beta commit=v0.14.2-beta
Calling getInfo() returns 
`thread 'main' panicked at 'failed to get info: Status { code: Unknown, message: "unmarshal v1: cannot parse field name", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None }'`

Any help would be appreciated. Thank you

**Comment by 0xBEEFCAF3** [comment]
Thank you @Kixunil! It was a problem with the macaroon. Closing

**Comment by Kixunil** [comment]
Glad you found out! Will be happy to hear how loptos works for you!
